# Generated by Django 2.1.5 on 2019-09-24 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('dateOfIssue', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Issue')),
                ('dateOfExpiration', models.DateTimeField(verbose_name='Date of Expiration')),
                ('totalSum', models.DecimalField(decimal_places=7, max_digits=7, verbose_name='Total sum')),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
